### ISSUE TITLE
Possibly remove pytest from required dependencies

### ISSUE THREAD

**Issue by AbeleMM** [SERG-Delft/dslinter#80]
Hi!

I have recently tried to install `dslinter` in a project where I was also using a version of `pytest > 3.10.1` and `pip install -r requirements.txt` errors out because of dependency conflicts between the two.

As far as I can tell, `pytest` is used in `dslinter` purely as a testing library, and is not required for actually running the tool. Thus, would it be possible to remove `pytest` (and, possibly, `pytest-cov`) from `pyproject.toml`, such that other projects using `dslinter` are not limited in their choice of `pytest` version?

**Comment by Hynn01** [comment]
Hi @AbeleMM ! Thank you for your suggestion! I've removed the pytest dependency in the PR and will release a new version soon :)

**Comment by AbeleMM** [comment]
Thanks a lot for the quick response!
